### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by Natalia-Katie** [smartnavdeep/Pig-Latin#14]
Hi Mr. Navdeep, can you be my friend ? please.

**Comment by smartnavdeep** [comment]
um..Look @Natalia-Katie, this isn't the place where you can talk cuz it's an official repository, other people will be seeing this, so please don't do like this in future, an issue in a repository is a section where you can report a bug about the program, not to chat, please don't take it personally I will have to close this issue, but before that please make a comment so that I can make sure that you have read this, btw, if you want to be my friend, then ok you are my friend from now, anyways if you do want to contact me in future, you can contact me in the smartnavdeep repository where you contacted me yesterday : )

**Comment by Natalia-Katie** [comment]
oh sorry for that Mr. Navdeep, you can close this issue, sorry for that again, anyways thank you for making me our friend 😉

**Comment by smartnavdeep** [comment]
and I think you should be sleeping now right ?

**Comment by Natalia-Katie** [comment]
Well yeah, bye 🙋‍♀️

**Comment by smartnavdeep** [comment]
yeah bye 🙋‍♂️
