### ISSUE TITLE
honestyyay?

### ISSUE THREAD

**Issue by Ved-programmer** [smartnavdeep/Pig-Latin#19]
When I type honesty, it becomes honestyyay. I am not sure if that is correct or not, could you confirm. If it is correct, then I will update my python code else you need to update your javascript code.

**Comment by smartnavdeep** [comment]
It is correct, because the pig Latin Program will only interfere with the starting of the word, it is the programs nature to produce like these words, so that ain't any problem, and again if it is really wrong, then the word `honesty` when translated might become `honestyay` and if we reverse translate this word, then It would become `honest`, that's why there is nothing wrong in the JavaScript code.

**Comment by Ved-programmer** [comment]
ok fine
